export const aboutText = [
  {
    header: "I am a person who:",
    listItems: [
      "Likes to build useful/interesting products",
      "Likes to explore new technologies",
      "Learns fast  ",
      "Can and is willing to learn anything required ",
      "Adapts quickly to new enironments",
      "Has a can-do mentality",
      "Does not need much supervision",
      "Is a team player",
      "Is funny & fun to work with",
      "Is hard working",
      "Is self motivating",
      "Loves dogs(have a pug)",
    ],
  },

  {
    header: "My key hobbies/interests:",
    listItems: [
      "Programming(web,mobile)",
      "DIY projects such as building a NAS with a Raspberry Pie",
      "3D printing",
      "Cryptocurrencies & Blockchain technologies",
      "Economics",
      "Decentrilization",
      ,
    ],
  },
  {
    header: "Professional Experience",
    listItems: [
      "Node.js",
      "Vue.js",
      "Php 7+",
      "Wordpress(Php)",
      "The holy trinity of HTML, CSS, JavaScript",
    ],
  },
  {
    header: "Hobby Experience",
    listItems: [
      "Swift(SwiftUI)",
      "React",
      "React Native",
      "Next.js",
      "Java",
      "Spring Boot",
      "Python 3",
      "Flask",
      "Solidity",
    ],
  },
  {
    header: "Tools used",
    listItems: [
      "Git/GitHub",
      "Firebase",
      "MongoDB",
      "RealmDB",
      "MySQL",
      "IPFS",
      "Metamask API",
      "OAuth",
      "XCode",
      "VsCode",
      "Postman",
      "Selenium",
      "Pupeteer",
      "Koa.js",
      "Express.js",
      "and many more",
    ],
  },
  {
    header: "My ideal workplace is:",
    listItems: [
      "Where I constantly learn and improve",
      "Where remote work is possible",
      "Where my work matters",
      "Family centric",
    ],
  },
  {
    header: "What I would like to improve in:",
    listItems: ["UI/UX", "Backend development", "Programming generally"],
  },
  {
    header: "What I value:",
    listItems: ["Honesty", "Integrity", "Transparency", "Good communication"],
  },
  {
    header: "Extras about me:",
    listItems: ["Hungarian nationality", "Can speak Croatian, and Hungarian"],
  },
  {
    header: "Education",
    listItems: [
      "Studied Computer Science at KEA, in Copenhagen",
      "Studied Economics at Business College of Budapest",
    ],
  },
];
